sudo: required
language: rust

# Cache cargo symbols for faster build
cache: cargo

# Dependencies of kcov, used by coverage
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake # also required for cargo-update
    sources:
      - kalakris-cmake

before_script:
  - cargo install -f cargo-travis
  - export PATH=$HOME/.cargo/bin:$PATH

script:
  - cargo test --all --verbose

after_success:
  - cargo coveralls --all --verbose
